run:
	go run gift.go items.go llm.go main.go papers.go score.go trigrams.go villagers.go db.go

build:
	CGO_ENABLED=1 go build -o server gift.go items.go llm.go main.go papers.go score.go trigrams.go villagers.go db.go
