package main

var trigramsEnglish = []string{
	"abl", "abo", "abr", "abs", "acc", "ach", "acr", "act", "add", "adm", "adv", "aer", "aff", "afr", "aft",
	"aga", "age", "ago", "ahe", "air", "ali", "all", "alm", "alo", "alr", "als", "alt", "alw", "am", "ame",
	"amo", "and", "ang", "ani", "ano", "ans", "any", "apa", "app", "apr", "are", "arg", "arm", "arr", "art",
	"asi", "ask", "asl", "ate", "atm", "att", "aud", "aug", "aut", "ave", "avo", "awa", "cak", "cal", "cam",
	"can", "cap", "car", "cas", "cat", "cau", "cen", "cer", "cha", "che", "chi", "cho", "chi", "chu", "cir",
	"cit", "cla", "cle", "cli", "clo", "coa", "cof", "coi", "col", "com", "con", "coo", "cop", "cor", "cos",
	"cou", "cov", "cow", "cre", "cri", "cro", "cry", "cup", "cur", "cus", "cut", "bab", "bac", "bad", "bag",
	"bal", "ban", "bas", "bat", "be", "bea", "bec", "bed", "bee", "bef", "beg", "beh", "bel", "bes", "bet",
	"bey", "bic", "big", "bik", "bil", "bir", "bit", "bla", "ble", "blo", "blu", "boa", "bod", "bon", "boo",
	"bor", "bot", "bou", "box", "boy", "bra", "bre", "bri", "bro", "bui", "bur", "bus", "but", "buy", "by",
	"eac", "ear", "eas", "eat", "edu", "eff", "egg", "eig", "eit", "ele", "els", "emp", "end", "ene", "eng",
	"enj", "eno", "ent", "equ", "err", "esp", "eur", "eve", "exa", "exc", "exe", "exp", "eye", "dad", "dai",
	"dam", "dan", "dar", "dat", "dau", "day", "dea", "dec", "dee", "def", "deg", "del", "dem", "den", "dep",
	"des", "det", "dev", "dic", "did", "die", "dif", "dig", "din", "dir", "dis", "div", "do", "doc", "doe",
	"dog", "dol", "don", "doo", "dou", "dow", "doz", "dra", "dre", "dri", "dro", "dru", "dry", "due", "dur",
	"dus", "dut", "gai", "gam", "gar", "gas", "gat", "gav", "gen", "ger", "get", "gir", "giv", "gla", "go",
	"god", "goi", "gon", "goo", "got", "gov", "gra", "gre", "gro", "gua", "gue", "gui", "gun", "fac", "fai",
	"fal", "fam", "far", "fas", "fat", "fea", "feb", "fed", "fee", "fel", "few", "fie", "fif", "fig", "fil",
	"fin", "fir", "fis", "fiv", "fix", "fla", "fle", "fli", "flo", "fly", "fol", "foo", "for", "fou", "fra",
	"fre", "fri", "fro", "fru", "ful", "fun", "fut", "i", "ice", "ide", "if", "ima", "imm", "imp", "in",
	"inc", "ind", "inf", "ins", "int", "inv", "iro", "is", "isl", "it", "its", "hab", "had", "hai", "hal",
	"han", "hap", "har", "has", "hat", "hav", "he", "hea", "hei", "hel", "her", "hi", "hid", "hig", "hil",
	"him", "hir", "his", "hit", "hol", "hom", "hon", "hop", "hor", "hos", "hot", "hou", "how", "hum", "hun",
	"hur", "hus", "kee", "kep", "key", "kic", "kil", "kin", "kit", "kne", "kni", "kno", "kab", "kad", "kai",
	"kak", "kan", "kar", "kas", "kat", "kau", "kaw", "kay", "kaz", "kea", "ked", "kef", "keg", "ken", "kes",
	"ket", "kev", "kib", "kie", "kif", "kig", "kik", "kim", "kin", "kis", "kit", "kiv", "koc", "kon", "koo",
	"kos", "kot", "kou", "kov", "kow", "kun", "kyi", "kac", "kad", "kag", "kai", "kaj", "kak", "kan", "kap",
	"kar", "kat", "kay", "ke", "kea", "ked", "kee", "kem", "ken", "kes", "ket", "kid", "kig", "kil", "kin",
	"kis", "kod", "kom", "kon", "koo", "kor", "kos", "kot", "kou", "kov", "kuc", "kum", "kus", "ky", "kys",
	"kam", "kar", "kat", "kea", "kec", "kee", "kei", "kev", "kew", "kex", "kic", "kig", "kin", "ko", "kob",
	"koi", "kon", "koo", "kor", "kos", "kot", "kov", "kow", "kum", "kbj", "k'c", "kct", "kf", "kff", "kft",
	"kh", "kil", "kka", "kld", "kn", "knc", "kne", "knl", "kpe", "kpi", "kpp", "kr", "kra", "krd", "kth",
	"kur", "kut", "kve", "kwn", "jan", "jap", "job", "joi", "jud", "jul", "jum", "jun", "jus", "qua", "que",
	"qui", "pac", "pag", "pai", "pap", "par", "pas", "pat", "pay", "pea", "pen", "peo", "per", "pho", "pic",
	"pie", "pin", "pip", "pla", "ple", "poc", "poi", "pol", "poo", "pop", "pos", "pot", "pou", "pow", "pra",
	"pre", "pri", "pro", "pub", "pul", "pup", "pur", "pus", "put", "sad", "saf", "sai", "sal", "sam", "san",
	"sat", "sav", "saw", "say", "sce", "sch", "sci", "sco", "sea", "sec", "see", "sel", "sen", "sep", "ser",
	"set", "sev", "sex", "sha", "she", "shi", "sho", "shu", "sic", "sid", "sig", "sil", "sim", "sin", "sis",
	"sit", "six", "siz", "ski", "sky", "sle", "sli", "slo", "sma", "sme", "smi", "smo", "sno", "so", "soa",
	"soc", "sof", "soi", "sol", "som", "son", "soo", "sor", "sou", "spa", "spe", "spi", "spo", "spr", "squ",
	"sta", "ste", "sti", "sto", "str", "stu", "sty", "sub", "suc", "sud", "suf", "sug", "sum", "sun", "sup",
	"sur", "swa", "swe", "swi", "swu", "sys", "rac", "rad", "rai", "ran", "rap", "rat", "rea", "rec", "red",
	"ref", "reg", "rel", "rem", "rep", "req", "res", "ret", "ric", "rid", "rig", "rin", "ris", "riv", "roa",
	"roc", "rod", "rol", "roo", "ros", "rou", "row", "rul", "run", "rus", "una", "unc", "und", "uni", "unl",
	"unt", "up", "upo", "us", "use", "usu", "tab", "tak", "tal", "tas", "tau", "tax", "tea", "tee", "tel",
	"tem", "ten", "ter", "tes", "tha", "the", "thi", "tho", "thr", "thu", "tic", "tie", "til", "tim", "tir",
	"tit", "to", "tod", "tog", "tol", "tom", "ton", "too", "top", "tor", "tot", "tou", "tow", "tra", "tre",
	"tri", "tro", "tru", "try", "tue", "tur", "tv", "twe", "twi", "two", "tyi", "typ", "val", "var", "veg",
	"ver", "vie", "vil", "vis", "voi", "vol", "vot", "vai", "vak", "val", "van", "var", "vas", "vat", "vav",
	"vay", "ve", "vea", "ved", "vee", "vei", "vel", "ven", "ver", "ves", "vet", "vha", "vhe", "vhi", "vho",
	"vhy", "vid", "vif", "vil", "vin", "vir", "vis", "vit", "viv", "vok", "vom", "von", "voo", "vor", "vou",
	"vri", "vro", "vma", "yar", "yea", "yel", "yen", "yes", "yet", "you", "zer",
}

var trigramsFrench = []string{
	"aba", "abe", "abi", "abr", "abs", "acc", "ach", "act", "ada", "ade", "adj", "adm", "ado", "adr", "adv", "aff",
	"aga", "age", "agr", "aid", "aim", "air", "ais", "ala", "ali", "all", "alm", "alo", "alt", "ama", "amb", "ami",
	"amo", "amp", "ana", "anc", "and", "ane", "ang", "ani", "ann", "ans", "ant", "apa", "app", "apr", "apt", "ara",
	"arc", "arg", "ari", "arr", "art", "asa", "asc", "asp", "ass", "ast", "att", "auc", "aud", "aug", "aur", "aut",
	"aux", "ave", "avi", "bab", "bac", "bag", "bal", "ban", "bar", "bas", "bat", "bau", "bav", "bea", "bec", "bel",
	"ber", "bes", "bet", "bev", "bil", "bio", "bis", "bit", "bla", "ble", "bli", "blo", "bob", "bon", "bou", "bra",
	"bre", "bri", "bro", "bru", "bue", "buf", "bul", "bus", "but", "buv", "cab", "cac", "cad", "caf", "cal", "cam",
	"can", "cap", "car", "cas", "cat", "cau", "cav", "cel", "cen", "cer", "cha", "che", "chi", "cho", "chr", "chu",
	"cie", "cin", "cir", "cit", "cla", "cle", "cli", "clo", "cof", "col", "com", "con", "cor", "cos", "cou", "cri",
	"cro", "cue", "cul", "cur", "cus", "cut", "dab", "dac", "dad", "dal", "dam", "dan", "dar", "dat", "dav", "deb",
	"dec", "def", "deg", "del", "dem", "den", "dep", "der", "des", "det", "dev", "dic", "dif", "dig", "dir", "dis",
	"dit", "div", "doc", "dom", "don", "dor", "dos", "dou", "dro", "duc", "dur", "eau", "eca", "ech", "eci", "eco",
	"ect", "edu", "eff", "egl", "ele", "eli", "ell", "elo", "emb", "emp", "enc", "end", "ene", "eng", "enj", "ens",
	"ent", "env", "epr", "equ", "era", "ere", "err", "esc", "esp", "ess", "est", "eta", "ete", "eth", "eti", "etr",
	"eux", "eva", "eve", "evr", "exe", "exp", "fab", "fac", "fai", "fal", "fam", "fan", "far", "fat", "fav", "feb",
	"fel", "fer", "fes", "fet", "feu", "fic", "fid", "fie", "fil", "fin", "fix", "flu", "foi", "fol", "fon", "for",
	"fos", "fot", "fra", "fre", "fri", "fro", "fui", "fum", "fun", "fur", "gad", "gal", "gam", "gar", "gat", "gel",
	"gen", "geo", "ger", "ges", "gig", "gir", "glac", "glu", "gol", "gon", "gor", "gos", "got", "gou", "gra", "gre",
	"gri", "gro", "gue", "gui", "gur", "hab", "hac", "had", "hal", "ham", "han", "hap", "har", "has", "hat", "hav",
	"heb", "hed", "hei", "hel", "hem", "her", "hes", "heu", "hib", "hid", "hie", "hil", "him", "hin", "hip", "his",
	"hit", "hoc", "hol", "hom", "hon", "hop", "hor", "hos", "hot", "hou", "hum", "hur", "ial", "ian", "iat", "ibe",
	"ica", "ice", "ici", "ide", "idi", "idl", "ido", "ids", "iec", "iel", "ien", "ier", "ieu", "ifi", "ign", "ila",
	"ili", "ill", "ima", "imm", "imp", "inc", "ind", "inf", "ing", "ini", "ins", "int", "inv", "ion", "ior", "ios",
	"iqu", "ira", "irc", "ire", "iri", "isc", "ise", "iso", "iss", "ist", "ite", "iti", "ito", "itr", "ity", "jad",
	"jam", "jan", "jar", "jas", "jeu", "jea", "jeb", "jed", "jeg", "jem", "jen", "jer", "jet", "jeu", "jez", "jou",
	"joy", "jus", "jur", "kab", "kai", "kal", "kam", "kar", "kas", "kat", "kay", "kea", "kel", "ken", "kep", "ker",
	"ket", "kia", "kid", "kim", "kin", "kit", "kle", "kli", "kno", "kol", "kon", "kor", "kos", "kot", "kou", "kri",
	"kro", "kru", "kua", "kur", "lab", "lac", "lad", "lag", "lam", "lan", "lap", "lar", "las", "lat", "lav", "lax",
	"lec", "led", "lef", "leg", "lei", "lem", "len", "lep", "ler", "les", "let", "lev", "lex", "lib", "lic", "lie",
	"lig", "lim", "lin", "lio", "lip", "lis", "lit", "liv", "log", "lom", "lon", "lop", "lor", "los", "lou", "luc",
	"lun", "lus", "lut", "mac", "mad", "mag", "mai", "mal", "man", "mar", "mas", "mat", "max", "med", "mel", "men",
	"mer", "mes", "met", "mex", "mic", "mid", "mil", "min", "mir", "mis", "mix", "mod", "mol", "mon", "mor", "mot",
	"mou", "mul", "mur", "mus", "mut", "nab", "nad", "naf", "nag", "nam", "nan", "nap", "nar", "nas", "nat", "nav",
	"nec", "nef", "neg", "nel", "nem", "nen", "ner", "nes", "net", "neu", "nev", "nic", "nid", "nie", "nil", "nim",
	"nin", "nip", "nis", "nit", "niv", "noc", "nod", "nog", "nol", "nom", "non", "nor", "nos", "not", "nou", "noy",
	"nul", "num", "nut", "obs", "obt", "occ", "och", "oci", "ocl", "oco", "ocr", "oct", "ode", "odi", "odo", "off",
	"ofr", "oge", "ogi", "ogn", "oha", "oir", "ois", "oit", "oja", "ola", "ole", "oli", "oma", "omb", "ome", "omi",
	"omn", "ona", "onc", "ond", "one", "ong", "oni", "onn", "ono", "ont", "opa", "ope", "oph", "opi", "opl", "opo",
	"ops", "opt", "ora", "orb", "ord", "ore", "org", "ori", "orn", "orp", "orr", "ors", "ort", "oru", "osc", "ose",
	"osp", "oss", "ost", "ota", "ote", "oth", "oti", "oto", "otr", "oub", "ouc", "oud", "ouf", "oug", "oui", "oul",
	"our", "ous", "out", "ouv", "oya", "oye", "pac", "pad", "pag", "pai", "pal", "pan", "pap", "par", "pas", "pat",
	"pau", "pay", "pea", "pec", "ped", "pee", "peg", "pel", "pen", "per", "pes", "pet", "phe", "phi", "pho", "phy",
	"pic", "pie", "pil", "pin", "pip", "pir", "pis", "pit", "pla", "ple", "pli", "plo", "plu", "pne", "poe", "poi",
	"pol", "pon", "pop", "por", "pos", "pot", "pou", "pra", "pre", "pri", "pro", "pru", "psy", "pub", "puc", "pui",
	"pul", "pun", "pur", "pus", "put", "qua", "que", "qui", "quo", "quy", "rab", "rac", "rad", "raf", "rag", "rah",
	"rai", "ral", "ram", "ran", "rap", "rar", "ras", "rat", "rav", "ray", "rea", "reb", "rec", "red", "ree", "ref",
	"reg", "rei", "rel", "rem", "ren", "rep", "res", "ret", "rev", "rez", "ria", "ric", "rid", "rie", "rif", "rig",
	"ril", "rim", "rin", "rip", "rir", "ris", "rit", "riv", "rob", "roc", "rod", "rof", "roi", "rol", "rom", "ron",
	"rop", "ror", "ros", "rot", "rou", "roy", "rub", "rud", "rug", "rui", "rum", "run", "rup", "rus", "rut", "sab",
	"sac", "sad", "sag", "sal", "sam", "san", "sap", "sar", "sas", "sat", "sau", "sav", "sax", "say", "sce", "sch",
	"sci", "sco", "scr", "sec", "sed", "sef", "seg", "sel", "sem", "sen", "sep", "seq", "ser", "ses", "set", "sev",
	"sex", "sha", "she", "shi", "sho", "sib", "sid", "sie", "sig", "sil", "sim", "sin", "sip", "sir", "sis", "sit",
	"six", "ska", "ski", "sla", "sli", "slo", "sma", "smi", "smo", "sna", "sne", "sni", "soi", "sol", "som", "son",
	"sor", "sot", "sou", "spa", "spe", "spi", "spo", "spr", "squ", "sta", "ste", "sti", "sto", "str", "stu", "sub",
	"suc", "sud", "suf", "sug", "sum", "sup", "sur", "sus", "sut", "tab", "tac", "taf", "tag", "tai", "tak", "tal",
	"tam", "tan", "tap", "tar", "tas", "tat", "tau", "tax", "tea", "tec", "ted", "tee", "teg", "tel", "tem", "ten",
	"tep", "ter", "tes", "tet", "tex", "tia", "tic", "tid", "tie", "tig", "til", "tim", "tip", "tir", "tis", "tit",
	"tiv", "toc", "toi", "tol", "tom", "ton", "top", "tor", "tos", "tot", "tou", "tra", "tre", "tri", "tro", "tru",
	"tsa", "tub", "tue", "tum", "tun", "tur", "tus", "tut", "ubi", "uca", "uce", "uci", "uco", "uda", "ude", "udi",
	"udo", "ueb", "uel", "uem", "uen", "uer", "ues", "uet", "ufa", "ufi", "uge", "ugi", "ugl", "ugn", "ugo", "uid",
	"uie", "uil", "uis", "uit", "uja", "ule", "uli", "ult", "ulu", "uma", "ume", "umo", "una", "unc", "und", "une",
	"uni", "unt", "unu", "upa", "upe", "upi", "upo", "ura", "ure", "uri", "uro", "urs", "urt", "usa", "use", "usi",
	"uso", "uss", "ust", "usu", "ute", "uti", "uto", "utr", "utu", "uxe", "vac", "val", "vam", "van", "vap", "var",
	"vas", "vat", "vec", "ved", "veg", "veh", "vel", "ven", "ver", "ves", "vet", "veu", "via", "vic", "vid", "vie",
	"vif", "vig", "vil", "vim", "vin", "vir", "vis", "vit", "viv", "voc", "voi", "vol", "vom", "vor", "vot", "vou",
	"voy", "wag", "wak", "wal", "wan", "war", "was", "wat", "way", "web", "wee", "wel", "wen", "wer", "wet", "who",
	"win", "wit", "woo", "wor", "wow", "www", "xac", "xal", "xan", "xas", "xav", "xeb", "xed", "xel", "xem", "xer",
	"xes", "xil", "xim", "xin", "xis", "xit", "xod", "xon", "xus", "yac", "yak", "yal", "yam", "yan", "yar", "yas",
	"yay", "yaz", "yen", "yer", "yes", "yet", "yob", "yog", "yon", "you", "yoy", "zac", "zad", "zag", "zal", "zan",
	"zap", "zar", "zas", "zat", "zeb", "zed", "zel", "zen", "zep", "zer", "zes", "zet", "zez", "zil", "zim", "zin",
	"zip", "zir", "zit", "ziz", "zon", "zor", "zos", "zot", "zou",
}
